# ===================== MongoDB Config =====================
spring.data.mongodb.database=${MONGODB_DATABASE:postkardbdev}

# ===================== Logging =====================
logging.level.org.springframework=${LOGGING_LEVEL_SPRING:DEBUG}
logging.level.com.ag.project=${LOGGING_LEVEL_PROJECT:DEBUG}

# Application name
spring.application.name=postkar

server.forward-headers-strategy=native

# File upload limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Cloudflare R2 Storage Configuration
cloudflare.r2.bucket=${CLOUDFLARE_R2_BUCKET:postkardev}
cloudflare.r2.endpoint=${CLOUDFLARE_R2_ENDPOINT:https://28d7f56b3627d31aca6c85d8a06c2519.r2.cloudflarestorage.com}

# App-specific settings
signed.url.expiry.hours=24
app.signed-url-expiry-minutes=1440
app.current-version=v1

spring.main.allow-circular-references=true
spring.http.client.factory=simple

